### ISSUE TITLE
redesigning our map

### ISSUE THREAD

**Issue by itahagai** [idoivri/airpollution#13]
map id: itahagai.ec6d50c7

@idoivri

**Comment by idoivri** [comment]
Hi @itahagai , I added the map ID but now the map tiles don't load :(

**Comment by itahagai** [comment]
ahhh @idoivri i'll see you at electra building at 19:00 with my files and we will try to fix it together

**Comment by idoivri** [comment]
No probs ;)

On Mon, Jun 8, 2015 at 4:29 PM, itahagai notifications@github.com wrote:

> ahhh @idoivri https://github.com/idoivri i'll see you at electra
> building at 19:00 with my files and we will try to fix it together
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/idoivri/airpollution/issues/13#issuecomment-109995973
> .

## 

-Ido

"There are 10 types of people in the world: those who understand binary,
and those who don't."
(unknown)

**Comment by itahagai** [comment]
thanks bro ;)

**Comment by itahagai** [comment]
https://api.tiles.mapbox.com/v4/itahagai.ec6d50c7/page.html?access_token=pk.eyJ1IjoiaXRhaGFnYWkiLCJhIjoiZmxIdGF5MCJ9.L_VBtl5noeLVHw_bIr4Hag#11/31.7261/34.4950

**Comment by idoivri** [comment]
Done :-) @itahagai , took some effort but I'm done ;) the map looks great.
